import ArticlesList from '@/components/ArticlesList';
import { CategoryTabs } from '@/components/CategoryTabs';
import SearchBar from '@/components/SearchBar';
import Head from 'next/head'
import { fetchArticles, fetchCategories } from './api'
import qs from "qs"

export default function Home(props) {
  const CategoryArr = props.categories //array of categories
  const ArticleArr = props.articles


  return (
    <>
      <Head>
        <title>Kollaborate-Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="https://kollaborate.co/_next/image?url=%2Fimages%2Flogo.png&w=48&q=75" />
      </Head>

      <main>
        <div className='flex justify-between'>
          <CategoryTabs categoryArr={CategoryArr} />
          <SearchBar />
        </div>

        <div className='w-full h-screen border-4 rounded-md border-gray-200 p-4'>
          <ArticlesList articlesList={ArticleArr} />
        </div>

      </main>

    </>
  )
}

export async function getServerSideProps() {
  const options = {
    populate: '*',
  }
  const queryString = qs.stringify(options);

  //fetch categories here
  const categories = await fetchCategories();
  //fetch articles here
  const articles = await fetchArticles(queryString);



  return {
    props: {

      categories: categories.data.data,
      articles: articles.data.data

    }, // will be passed to the page component as props
  }


}


